docs:added guide for new users
Real-Dev-Squad/docs pull request #23
Opened 2024-01-26 00:01 UTC by tejaskh3

Date: 26-01-2024

Developer Name: Tejas

---

## Issue Ticket Number

## Description
This documentation contains the guide for new developers which can reduce the waiting time to get assigned with task.

2024-01-26 09:03 UTC, iamitprakash requested changes
can you add preview of md file

2024-01-27 06:56 UTC, tejaskh3 commented
> can you add preview of md file

For this, when you open my commit and start reading it this will show an option just click on that to view readme file.
attaching an image for reference and some steps.
1. click on "commit" above. 
2. Then open the file in which I have committed the changes and press the button in image.
![image](https://github.com/Real-Dev-Squad/docs/assets/98630752/17f84460-c264-4bce-9564-b0e9ea06f389)

And then anyone will be able to view Readme

2024-01-29 15:43 UTC, satyam73 requested changes

2024-01-29 15:43 UTC, satyam73 commented on docs/New User Guide/README.md
> +1. **Using the Website or Set-Up Projects:**
```suggestion
1. **Finding on you own:**

```

2024-01-29 15:43 UTC, satyam73 commented on docs/New User Guide/README.md
> +   - Set a reasonable time limit for task completion, the time you will need to get your code to production.
```suggestion
   - Set a reasonable time limit for task completion, the time you will need to get your code to **production**. Once again, the time you entering here will be the time in which your code is in the **production** and ready to use(not any intermediary state).
```

2024-01-29 15:43 UTC, satyam73 commented on docs/New User Guide/README.md
> +   - Tag Ankush, Tejas, or Prakash, requesting approval using channels `new-tasks` or `i-am-idle` for on discord.
```suggestion
   - Tag Ankush, Tejas, or Prakash, requesting approval using channels `new-tasks` or `i-am-idle` on discord.

```

2024-01-29 15:43 UTC, satyam73 commented on docs/New User Guide/README.md
> +By following these steps, you are all set to work on your assigned task. If you have questions, feel free to ask.
```suggestion
By following these steps, you are all set to work on your assigned task. If you have questions, feel free to ask in the server's respective channel.

```

2024-01-29 16:36 UTC, satyam73 approved these changes
LGTM

2024-01-29 20:11 UTC, iamitprakash approved these changes

2024-01-29 20:11 UTC, merged